language: generic
services:
  - docker
jobs:
  include:
    - stage: Build & Push Image
      before_script:
        - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      script:
        - docker build -t spounge/time_manager -f docker/api/Dockerfile .
        - docker push spounge/time_manager
    - stage: Deploy
      script: skip
      deploy:
        - provider: elasticbeanstalk
          region: 'eu-west-3'
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key:
            secure: $AWS_SECRET_ACCESS_KEY
          app: 'TimeManager'
          env: 'Timemanager-env'
          bucket_name: 'elasticbeanstalk-eu-west-3-254650023808'
          bucket_path: 'application/TimeManager'
