version: "3.8"
services:
  phoenix:
    build:
      args:
        - APP_PATH=./backend/
        - PGHOST=${PGHOST}
        - PGDATABASE=${PGDATABASE}
        - PGPASSWORD=${PGPASSWORD}
        - PGPORT=${PGPORT}
        - PGUSER=${PGUSER}
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      - PGHOST
      - PGDATABASE
      - PGPASSWORD
      - PGPORT
      - PGUSER
    image: spounge/time_manager
    ports:
      - 80:4000
  db:
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
    expose:
      - 5432
    image: postgres:13
